In [1]:
# MAIN ASSIGNMENT 5: EXERCISES 0-2
# GROUP 9
# Mangalaviti Matteo
# Marrone Tiziano
# Massaria Michele Domenico
# Vighi Virginia
%load_ext autoreload

In [14]:
%autoreload
import random

import pandas as pd
import numpy as np
from datetime import datetime
import utilities as ut

In [3]:
# EXERCISE 0
df = pd.read_csv('EUROSTOXX50_2023_Dataset.csv', index_col=0)  # We read the csv file and convert it in a dataframe on python
name_stocks0 = ['ADSGn.DE', 'ALVG.DE', 'MUVGn.DE', 'OREP.PA']  # We select the required stocks for the Exercise 0
dates_num = ['2016-03-18', '2019-03-20']  # We choose a 3y estimation starting from today (20th March 2019)
dates_den = ['2016-03-17', '2019-03-19']  # And going backward up to the first business day before 21st March 2016
# We call our read csv function to convert the dataframe in numpy arrays, paying attention to the missing values
np_num, np_den = ut.read_our_CSV(df, name_stocks0, dates_num, dates_den)
# Parameters
alpha = 0.95
notional = 1e7
delta = 1
n_asset = 4
weights = np.ones((n_asset, 1))/n_asset  # We consider an equally weighted portfolio
returns = np.log(np_num/np_den)  # Computation of the returns
# We compute the VaR and the ES using a Gaussian parametric approach
VaR, ES = ut.AnalyticalNormalMeasures(alpha, weights, notional, delta, returns)
print("VaR_0:", VaR, "ES_0:", ES)
# We check the result with a Plausibility check to estimate the order of magnitude of portfolio VaR
VaR_check = ut.plausibilityCheck(returns, weights, alpha, notional, delta)
print("VaR check_0:", VaR_check)

# EXERCISE 1.a
# Parameters
sett_date1 = '2019-03-20'
alpha_1 = 0.99
dates_num1 = dates_num
dates_den1 = dates_den  # 3y estimation as before
shares1 = np.array([25000, 20000, 20000, 10000])
Nsim = 200
name_stocks1a = ['TTEF.PA', 'DANO.PA', 'SASY.PA', 'VOWG_p.DE']  # We select the required stocks for the Exercise 1a)
stockPrice_1a = df.loc[[sett_date1], name_stocks1a].to_numpy()  # We extract the price of the stocks at the sett_date
# and then we convert the chosen row in a numpy array to perform calculation
ptf_value1a = shares1.dot(stockPrice_1a.T)  # Value of the portfolio
weights_1a = (shares1 * stockPrice_1a / ptf_value1a).T  # We compute the corresponding weight of each stock related with its number of shares
np_num1a, np_den1a = ut.read_our_CSV(df, name_stocks1a, dates_num1, dates_den1)
logReturns_1a = np.log(np_num1a / np_den1a)

VaR_0: 146813.58536847658 ES_0: 185434.4799413243
VaR check_0: 139905.9213679971


In [15]:
# EXERCISE 1.c
# Parameters
N = 20
df_1c = df.loc[:, df.columns != 'ADYEN.AS']  # We remove the column corresponding to the Adyen stock due to missing data
df_1c = df_1c.iloc[:, :N]  # We select the first 20 stocks of the new dataset
name_stocks1c = df_1c.columns
np_num1c, np_den1c = ut.read_our_CSV(df, name_stocks1c, dates_num1, dates_den1)
logReturns_1c = np.log(np_num1c/np_den1c)
n_asset1c = len(name_stocks1c)
weights_1c = np.ones((n_asset1c, 1))/n_asset1c  # We have to consider as above an equally weighted ptf
ptf_value1c = 1e8
days_VaR1c = 10  # Now the VaR must be computed at 10 days
n = range(1, 21)  # Parameter used for the PCA
# Initialization
ES_PCA = np.zeros((len(n), 1))
VaR_PCA = np.zeros((len(n), 1))
yearlyCovariance = np.cov(logReturns_1c.T)  # We compute the Variance Covariance Matrix of the returns
yearlyMeanReturns = np.mean(logReturns_1c, axis=0)  # We compute the mean of each
# column(i.e.columns <-> returns of the stocks) of the matrix of the returns, then we reshape it to have a column vector
for i in n:
    # for each i in the set of n we compute the PCA increasing at each iteration the number of principal components to be considered
    ES_PCA[i-1], VaR_PCA[i-1] = ut.PrincCompAnalysis(yearlyCovariance, yearlyMeanReturns, weights_1c, days_VaR1c, alpha_1, i, ptf_value1c)
print("VaR_PCA:", VaR_PCA, "ES_PCA:", ES_PCA)
# CHECK
VaR_check_PCA = ut.plausibilityCheck(logReturns_1c, weights_1c, alpha_1, ptf_value1c, days_VaR1c)
print("VaR_check_PCA:", VaR_check_PCA)

[[-9.24079168e-04]
 [-3.92826190e-04]
 [-9.90669411e-04]
 [-4.43423304e-04]
 [-1.76386076e-04]
 [ 1.03791991e-04]
 [ 1.16439082e-04]
 [ 5.97032117e-05]
 [-5.37171215e-04]
 [-1.97564683e-04]
 [ 7.58777196e-05]
 [-3.04632011e-04]
 [-1.05900265e-04]
 [ 3.03837488e-04]
 [-4.17949210e-05]
 [-5.00447216e-04]
 [-2.24415917e-05]
 [-2.33190022e-04]
 [-1.78761777e-04]
 [-9.36214678e-04]]
[0.02782071]
[[-9.24079168e-04]
 [-3.92826190e-04]
 [-9.90669411e-04]
 [-4.43423304e-04]
 [-1.76386076e-04]
 [ 1.03791991e-04]
 [ 1.16439082e-04]
 [ 5.97032117e-05]
 [-5.37171215e-04]
 [-1.97564683e-04]
 [ 7.58777196e-05]
 [-3.04632011e-04]
 [-1.05900265e-04]
 [ 3.03837488e-04]
 [-4.17949210e-05]
 [-5.00447216e-04]
 [-2.24415917e-05]
 [-2.33190022e-04]
 [-1.78761777e-04]
 [-9.36214678e-04]]
[0.02791443]
[[-9.24079168e-04]
 [-3.92826190e-04]
 [-9.90669411e-04]
 [-4.43423304e-04]
 [-1.76386076e-04]
 [ 1.03791991e-04]
 [ 1.16439082e-04]
 [ 5.97032117e-05]
 [-5.37171215e-04]
 [-1.97564683e-04]
 [ 7.58777196e-05]
 [-

In [7]:
a=[1.66724398e-03, 3.15604421e-04, 2.00597443e-04, 1.80840028e-04,
       1.63372771e-04, 3.55260707e-05, 1.46248722e-04, 1.34894262e-04,
       1.22905875e-04, 1.19732910e-04]
b=[1.16434997e-04, 1.00799800e-04,
       4.29317595e-05, 5.05539709e-05, 5.68393866e-05, 5.40921517e-05,
       8.31583520e-05, 7.34406334e-05, 7.86605876e-05, 7.64127428e-05]
array=np.array([a,b]).reshape(len(a),2)
df=pd.DataFrame(array,columns=['eig','mean'])
df


eig      mean
0  0.001667  0.000316
1  0.000201  0.000181
2  0.000163  0.000036
3  0.000146  0.000135
4  0.000123  0.000120
5  0.000116  0.000101
6  0.000043  0.000051
7  0.000057  0.000054
8  0.000083  0.000073
9  0.000079  0.000076

In [34]:
df.sort_values(by='eig',ascending=False)

eig      mean
0  0.001667  0.000316
1  0.000201  0.000181
2  0.000163  0.000036
3  0.000146  0.000135
4  0.000123  0.000120
5  0.000116  0.000101
8  0.000083  0.000073
9  0.000079  0.000076
7  0.000057  0.000054
6  0.000043  0.000051